package(default_visibility = ["//visibility:public"])

cc_binary(
	name = "rknn_common_test_mp",
	srcs = ["main.cc"],
	deps=[
        "//third_party/rknn:rknnrt_lib",
        "//mediapipe/framework/port:opencv_core",
        "//mediapipe/framework/port:opencv_imgcodecs",
        "//mediapipe/framework/port:opencv_imgproc",
    ]
)